title: Silo

description: >
  An API for reading and writing a wide diversity of binary, scientific data to be easily shared and exchanged.
  Silo is used by the <a href="https://visit.llnl.gov">VisIt</a> visualization tool.

theme: minima

minima:
  skin: solarized-light

exclude: [docs, src]

show_downloads: false

headers:
