title: Silo
author:
  name: markcmiller86
  email: miller86@llnl.gov

description: >
  An API for reading and writing a wide diversity of binary, scientific data to be easily shared and exchanged applications.
  Silo is used by the [VisIt](https://visit.llnl.gov) visualization tool.

theme: minima

minima:
  skin: solarized-light

exclude: [docs]

show_downloads: false
